[workspace]
members = ["macros"]

[package]
name = "sap"
version = "0.0.1"
edition = "2024"
description = "Small Argument Parser"
license = "Apache-2.0"
authors = ["Matilde Morrone <contact@morrone.dev>"]
repository = "https://github.com/morr0ne/sap"
readme = "README.md"
documentation = "https://docs.rs/sap"
include = ["src/**/*.rs", "README.md", "LICENSE"]

[profile.release]
lto = true
codegen-units = 1
strip = true
panic = "abort"

[dependencies]
# sap_macros = { version = "0.1.0-alpha.1", path = "./macros" }

[dev-dependencies]
anyhow = "1.0.97"
